### PR TITLE
New update for cuberite.org

### LINKED ISSUE #24: Enlarge page contents
The current size of the page content font is too small and really hard to read

### LINKED ISSUE #34: Button arrangement
In my humble opinion, in order to maximize UX, the following buttons should be:
- Literally 1 click away.
- Visible without scrolling to footer.

The buttons are:
- Forum
- Manual
- Plugins
- The download buttons
- Contribute
- Compile

Currently, `Forum` and `Manual` do not meet the above criteria. I think this can be achieved by making the following changes:

**Top bar:**
Home, **Forum**, **Manual**, Plugins, Support, contribute (Removed Discuss, blog, added forum, manual)

**Just below the Windows download buttons:**
Compile Cuberite, Github Repo (Unchanged)

**Footer:** (These don't have to meet the above criteria since they are less important)
Donate, **IRC**, Newsletter, Api Docs, License (added IRC)

**Summary**
- Removed `discuss` and `blog`, creating two empty slots at the top bar.
- Moved `forum` and `manual` to the top bar, reoccupying the freed slots.
- Added `IRC` to the footer.
- Blog is unused anyways, its removal is fine.
- Discuss would become redundant once IRC is added to footer, its removal is fine.

Tell me what you think.

Edit: Mostly typos.
Edit2: Removed blog.

### LINKED ISSUE #36: Add a banner to advertise the meetup
> Okay, by the looks of it, the meeting will happen at the end of February from the 19th to the 21th. "Registrations" to the meetup are just for statistics, so that I can see how many of you will come: http://doodle.com/poll/ywaucxvcyzstt36z
> 
> The location is mentioned in the Doodle poll. It's a local hackerspace.

– taken from the forum

### LINKED ISSUE #38: Add FreeBSD builds
I think at this point we have to overthink the website design. The main page will be totally cluttered if we add another two of those huge buttons. What about a download section instead?

### LINKED ISSUE #40: Proper download section
I'm imagining something like what the blender website is using: 
https://www.blender.org/download/

### PR DESCRIPTION
**Pull request by mathiascode**
Here's the large update I promised to make. Changes:
- Code cleanup
- Layout is much more responsive and doesn't look weird on larger screens (fixes #24 and #16)
- Better icon alignment
- Buttons rearranged (fixes #34)
- The "blog" and newsletter pages are merged
- Recent newsletters on "News" page
- Banner and post about the Cuberite meetup (fixes #36)
- Added FreeBSD downloads (fixes #38)
- New download button system (fixes #40)

Preview: http://final.cuberite.ga/

### CODE REVIEW

**Comment by sphinxc0re** [comment]
Looks very good. I think we can merge this for now. Could set up a PR to be merged right before the 19th of February which contains the YT/Twitch link + the meetup agenda?

**Comment by mathiascode** [comment]
That sounds good.

**Comment by sphinxc0re** [comment]
That would be great. BTW could you pm me your email address for further contact? And also are you attending the meetup in person?

**Comment by mathiascode** [comment]
I'm afraid I won't be able to attend the meetup. Sorry.

I've sent a PM on the forum.

**Pull request merged**
