### PR TITLE
Small fixes and changes

### PR DESCRIPTION
**Pull request by mathiascode**
- Removed Wiki link until we combine the User Manual and Wiki, and update the information (requested by Sawfat: http://forum.mc-server.org/showthread.php?tid=434&pid=23052)
- Added FAQ link instead of the Wiki link
- Removed oneclick.html, since it's not used and shows up in the sitemap
- Made the <title> tag look better
- Removed http://mathias-github.github.io/cuberite-redesign/ from font URLs
- Fixed icon height issue on the home page

### CODE REVIEW

**Comment by sphinxc0re** [comment]
I understand, that we don't need the wiki reference, but @madmaxoft did a lot of work on applying for a gratipay organization, so why should we remove it. ALSO @madmaxoft should invite all 'core-developers' to the organization

**Comment by bearbin** [comment]
I believe gratipay is basically completely broken, so we may actually want to remove it.

**Comment by sphinxc0re** [comment]
doesn't seem so https://gratipay.com/

**Comment by mathiascode** [comment]
The Gratipay link is already located on the "Contribute" page, along with text describing what the donations are used for.

**Comment by mathiascode** [comment]
Maybe a better idea: If you prefer, I can replace the Wiki link with the FAQ link. (I just want the footer to be symmetrical.)

**Comment by sphinxc0re** [comment]
I think the donate link should stay as well

**Comment by mathiascode** [comment]
Yep. I'll leave that and replace the Wiki link with the FAQ link.

**Comment by mathiascode** [comment]
Done

**Comment by mathiascode** [comment]
I take the opportunity to improve the <title> tag content before this pull request is merged. :P

**Comment by tigerw** [comment]
I take the opportunity to improve your formatting; also, you broke the GitHub's markdown formatter! yay~

**Comment by mathiascode** [comment]
Oops

**Comment by mathiascode** [comment]
So, can this be merged? Is there anything I should change still?

**Comment by mathiascode** [comment]
Looks like I forgot to remove http://mathias-github.github.io/cuberite-redesign/ from the font URLs before making the first PR. I've removed it now.

This PR can be merged now.

**Comment by madmaxoft** [comment]
I've just noticed that at certain window sizes the layout breaks slightly, the bottom icons are not at the same height:
mcs_web_redesign_layout_break
Any way to fix that?

**Comment by madmaxoft** [comment]
As for gratipay, it's basically broken, I can't edit the organization (tried to rename, to no avail), there's no way to invite other people to join it, and there's no funds anyway.

**Comment by mathiascode** [comment]
The icon issue can be fixed. Thanks for pointing it out. Demo at http://final.cuberite.ga once it finishes buliding.

Is there another location to donate, or should I remove all references to donations?

**Comment by mathiascode** [comment]
Bump?

**Comment by bearbin** [comment]
I think oneclick.html is linked to from somewhere else so we shouldn't remove it. Apart from that it looks good.

**Comment by mathiascode** [comment]
Alright, I re-added oneclick.html and hid it from the sitemap. I also fixed the icon height problem.

Let's get this PR merged before it becomes too messy. The donation link can be handled in another PR.

**Pull request merged**
