### PR TITLE
News forum link

### PR DESCRIPTION
**Pull request by SafwatHalaby**
I have added links to the forum as described in #44
However, the template does not use them yet. This needs a bit more work, I'd be great if someone can take it from here.

### CODE REVIEW

**Comment by mathiascode** [comment]
I'll take care of the template

**Comment by SafwatHalaby** [comment]
I have updated the templates. But I am no desginer and I did not test the output. If someone one would like to apply their artistic touch on this, by all means go ahead.

**Comment by SafwatHalaby** [comment]
@mathias-github Note that ideally, the template should not barf if no link is provided. We might post it at the site before we post it at the forum, so there will be a timegap without a link.

**Comment by mathiascode** [comment]
That shouldn't be a problem

**Comment by LogicParrot** [comment]
Should I undo my template changes?

**Comment by SafwatHalaby** [comment]
I removed my template changes.

**Comment by mathiascode** [comment]
Do you like this template? http://final.cuberite.ga/news/cuberite-meetup/

The code for the link is hidden when there is no forum link specified: http://final.cuberite.ga/news/welcome-to-the-news/

**Comment by SafwatHalaby** [comment]
In my opinion the button should be a bit more prominent.
Is there a short way to say "Read existing comments or leave a comment" rather than "leave a comment"?

**Comment by mathias-github** [comment]
Perhaps "Discuss this article"?

**Comment by mathiascode** [comment]
Perhaps "Discuss this post"?

Preview: http://final.cuberite.ga/news/cuberite-meetup/

**Comment by SafwatHalaby** [comment]
"Discuss this post" sounds good to me :)

**Comment by mathiascode** [comment]
Alright! :) 
Do you want me to push the changes directly to the repository?

**Comment by SafwatHalaby** [comment]
Ok. I will close this PR then.

**Pull request closed without merging**
