### PR TITLE
Removed bountysource Donate link

### PR DESCRIPTION
**Pull request by williamhatcher**
From what I can tell, we don't use Bounty Source (much) anymore,
So I propose we remove it.

### CODE REVIEW

**Comment by mathiascode** [comment]
Bountysource is still used by the project.

**Comment by williamhatcher** [comment]
Ok. Maybe promote it more?

**Comment by mathiascode** [comment]
Any ideas where? The link is already in the footer, on the contribute page and in the README of the cuberite repository.

**Comment by williamhatcher** [comment]
Send out a reminder in the newsletter?

**Comment by bearbin** [comment]
I will send something out through the newsletter, but unfortunately there haven't been any few subscribers for the last year really.

**Comment by mathiascode** [comment]
I guess it would be time for an update post (last one was in January), which we could publish on the website and forums too.

**Pull request closed without merging**
