### PR TITLE
Plugin information update

### PR DESCRIPTION
**Pull request by mathiascode**
I added a link to the user's manual for information on adding plugins to a server. I also moved the plugin development information from contribute.html to plugins.html.

Preview: http://final.cuberite.ga/

### CODE REVIEW

**Comment by SafwatHalaby** [comment]
- Something is wrong with the seperators, they are too close to `Compile Cuberite`. An image is attached.
- Minor nitpicking: Humans read left to right. The manual should probably be the leftmost, since the majority of readers aren't  devs. And the code repo should be rightmost, since many will compile even though they aren't devs.

**Comment by SafwatHalaby** [comment]
Other than the two remarks above, lgtm.

I think the `support` page should consists 4 buttons rather than a long string. (`forum`, `faq`, `manual`, `Support Email`). But that probably deserves a seperate PR.

**Comment by mathiascode** [comment]
Those changes aren't included in this PR. I'm still experimenting with them in my own repo.

**Comment by SafwatHalaby** [comment]
My bad.

**Comment by SafwatHalaby** [comment]
Any objections to merge?

**Pull request merged**
