### PR TITLE
The new design for Cuberite.org

### PR DESCRIPTION
**Pull request by mathiascode**
Discussed here: http://forum.mc-server.org/showthread.php?tid=2049
Live preview: http://mathias-github.github.io/cuberite-redesign/

### CODE REVIEW

**Comment by sphinxc0re** [comment]
you removed the .nojekyll file. You should recreate it unless you are using jekyll

**Comment by mathiascode** [comment]
I am using Jekyll.

**Comment by sphinxc0re** [comment]
I think you should try to move the logo more into foreground. So that we get some trademark recognition

**Comment by mathiascode** [comment]
Can we wait with that until we get a permanent logo?

**Comment by sphinxc0re** [comment]
Yep. but then we have to wait for this to be happening in order to get this pr merged

**Comment by mathiascode** [comment]
Correct. We need to get a poll created for the logo. I won't be home for a few days though, so I can't create one right now.

**Comment by bearbin** [comment]
Can you clarify why you replaced the piwik javascript with the image? The image works as a hit tracker, but has none of the other features (referrers, clickthroughs and other things), and the javascript has no impact on page load time, as it is downloaded and executed after the rest of the page has rendered.

**Comment by bearbin** [comment]
The design is great, BTW :)

**Comment by mathiascode** [comment]
At first I wanted the site to be pure HTML and CSS, and I also though the image would be faster. Afterwards I realised that the loading speeds of the image and JS are almost identical. I'll add the JS code back in the next PR.

**Comment by mathiascode** [comment]
Thanks!

**Comment by mathiascode** [comment]
May I disable the cookies for the script, or does it have a big impact on the analytics? I'd rather not add some crappy cookie message on the site. :P

**Comment by bearbin** [comment]
Cookies are a fairly important part of the script. I just wouldn't bother with the stupid cookie message if it was me (maybe put a notice next to the copyright one in the footer?) but I don't know if other countries take it more seriously than the UK.

**Comment by mathiascode** [comment]
We don't even have a privacy policy or ToS, so I won't bother with the cookie message/banner. I don't think anyone will care.

**Comment by tigerw** [comment]
@mathias-github, flouting the law since 2015

**Comment by mathiascode** [comment]
:P

Maybe I'll write a short privacy policy later. It doesn't have to be as long as every other one.

**Comment by mathiascode** [comment]
@bearbin Is there any reason to why the user manual isn't hosted on Github Pages? Can it be moved to the main site?

**Comment by bearbin** [comment]
Yes. The design is not manually updated plain HTML, there is a generation step so it can't just be static.

**Comment by sphinxc0re** [comment]
Any updates on this one?

**Comment by mathiascode** [comment]
I've been away for a week, so I haven't had a chance to work on this. I'll make some changes soon.

**Comment by sphinxc0re** [comment]
It would be nice if you could include the glyph logo on the top left corner but also the colored logo on the frontpage. Also a home section would be nice, just for usability.

EDIT: Someone should come up with a better background design. Something more Minecrafty + Cuberitey

**Comment by sphinxc0re** [comment]
What about a star counter like this http://ghbtns.com/
Only we have to change the style a little bit

**Comment by mathiascode** [comment]
What would a home section contain?

If anyone has any ideas for the background, you're welcome to share them.

I personally don't like the star counter, as I think the site becomes too cluttered. I'll see if I can squeeze one in somewhere though.

**Comment by sphinxc0re** [comment]
For the home seciton: ATM there is a home, but there is no way to get to it other than  clicking on the logo

**Comment by mathiascode** [comment]
A home button in the navigation bar?

**Comment by sphinxc0re** [comment]
Yes :smile:

**Comment by worktycho** [comment]
UI wise, This increases the clicks to download from one to two. Why?

**Comment by sphinxc0re** [comment]
Yeah also I really would like it more if we had a 'Download' section in the navbar and the download button would lead there

**Comment by mathiascode** [comment]
@worktycho Either you'd have to scroll down the page to the download links or click a button to open a popup. I personally don't think one extra click (on a big button) instead of scrolling is too bad.

@SphinxC0re I added "Home" and "Download" to the navbar in the live demo. Still working on the big icon position and size (I don't think the colored icon fits in very well. What do you think?)

**Comment by worktycho** [comment]
Or you decrease the size of the logo and title text. A user navigating to download the server is not interested in the logo, and will already have got the name, either from the url, or the title in a search engine.

**Comment by sphinxc0re** [comment]
That's not what I meant. I mean, you should ditch the modal download dialog and let it have it's own page

**Comment by mathiascode** [comment]
@worktycho Made some changes in the live preview. What do you think? It's just a quick move from the download popup, so the padding/margin isn't adjusted well yet.

**Comment by worktycho** [comment]
I think that's better. We want it to be as easy as possible to download.

**Comment by madmaxoft** [comment]
I think the icons on the download buttons could be larger, they are now at the edge of recognizability. Other than that, I love the redesign.

**Comment by sphinxc0re** [comment]
In my opinion, the background is still too dark. Also it is not (Minecrafty|Cuberity) enough

**Comment by mathiascode** [comment]
The background is the hard part. :/ If anyone has some ideas, please share them.

**Comment by mathiascode** [comment]
@SphinxC0re How is this shade of blue? Still too dark?

**Comment by sphinxc0re** [comment]
Try something blue-greenish. Also http://color.adobe.com
Try to find a color fitting the green of the download buttons

**Comment by sphinxc0re** [comment]
Also why coloring the buttons green? What about coloring them in the colors of the corrending operating system?

**Comment by sphinxc0re** [comment]
bildschirmfoto von 2015-08-08 10-23-52
Still very dark, but a little easier to read and look at

**Comment by mathiascode** [comment]
What's the license of the background? Looks a bit better indeed.

**Comment by mathias-github** [comment]
Sorry for being away so much lately. Needed a little break from working at this design.

**Comment by sphinxc0re** [comment]
It's from http://subtlepatterns.com/?s=dark idk what license it is

**Comment by wbrbr** [comment]
See http://subtlepatterns.com/about/ : 

> **Is it OK to use your patterns in commercial projects?**
> 
> Yes it is, as long as you credit subtlepatterns.com some where in the project.

Cuberite is not a commercial project but I think we should still credit subtlepatterns.com

> **How do I credit you on my site?**
> 
> You can credit using a comment in your HTML or CSS code. Example for CSS:
> `/* Background pattern from subtlepatterns.com */`

**Comment by sphinxc0re** [comment]
Yeah, that would be good

**Comment by sphinxc0re** [comment]
bildschirmfoto am 2015-08-14 um 22 40 26

**Comment by sphinxc0re** [comment]
Background image sincerely by me :+1: 
cuberite_baclground

**Comment by sphinxc0re** [comment]
Also, is it possible to build a blog section with jekyll?

**Comment by tigerw** [comment]
Very psychedelic. Consider a little CSS `filter: blur(2px)`? Nice graphics work!

**Comment by sphinxc0re** [comment]
Thank you very much :D

**Comment by sphinxc0re** [comment]
Also this isn't even my PR :laughing:

**Comment by SphinxC0re** [comment]
Here is another trial
backgroundimage

**Comment by sphinxc0re** [comment]
cuberite_baclground_2

**Comment by sphinxc0re** [comment]
bildschirmfoto am 2015-08-15 um 16 01 28

**Comment by mathiascode** [comment]
Looks like cheap shiny plastic cubes. :P

**Comment by mathiascode** [comment]
A blog section should be possible (if anyone is willing to write something in it).

**Comment by mathiascode** [comment]
I need to stop being lazy and finish this PR soon. :S

**Comment by NiLSPACE** [comment]
I think that background would stand out too much. Perhaps add a transparent div above it?

**Comment by sphinxc0re** [comment]
I am willing to write into that blog. But the blog should have a more consistent background ^^

**Comment by sphinxc0re** [comment]
Also you are still able to choose between those two backgrounds

**Comment by mathiascode** [comment]
I'd rather use the subtlepatterns background you provided first. The others are distracting and don't really fit in with the design in my opinion (I appreciate that you took time to create those backgrounds though). Is it okay for you? :)

**Comment by sphinxc0re** [comment]
Yeah :+1:

**Comment by mathiascode** [comment]
Working on a new color scheme. Tell me if you like it or hate it. :P 
http://mathias-github.github.io/cuberite-redesign/

**Comment by sphinxc0re** [comment]
I really like it. But you should now try to insert the logo for brand recognition. Also you should make the font and icon inside the buttons bigger

**Comment by mathiascode** [comment]
Thanks!

Is it not enough with the logo in the navigation bar?

The buttons should be pretty much done now. I've increased the font and icon size.

**Comment by sphinxc0re** [comment]
The head title should also say: A custom Minecraft compatible game server written in C++

**Comment by mathiascode** [comment]
Does not look good in lowercase in my opinion. :/

**Comment by sphinxc0re** [comment]
That's not the point. The main and the head title aren't the same

**Comment by mathiascode** [comment]
Whatever, as you wish.

**Comment by sphinxc0re** [comment]
No :smile: it's not about CASE. UPPER CASE is fine, it's great

**Comment by sphinxc0re** [comment]
``` html
<title>A custom Minecraft compatible game server written in C++</title>
```

**Comment by mathiascode** [comment]
Oh, that title. I see. :)

**Comment by mathiascode** [comment]
Changed.

**Comment by sphinxc0re** [comment]
Great, now change the case back like it was before :smile:

**Comment by mathiascode** [comment]
Already done. :+1:

**Comment by mathiascode** [comment]
Trying to make the blog work at the moment.

**Comment by sphinxc0re** [comment]
nice

**Comment by sphinxc0re** [comment]
Bloooooooooooog!!!

**Comment by mathiascode** [comment]
It's happening! :D

**Comment by sphinxc0re** [comment]
could you try to brighten up the website a little more?

**Comment by mathiascode** [comment]
How is the color now?

**Comment by sphinxc0re** [comment]
I thought more of #025203

**Comment by mathiascode** [comment]
That's exactly the color I've defined in the CSS ?

**Comment by sphinxc0re** [comment]
#008602

**Comment by sphinxc0re** [comment]
I got another pattern:
bildschirmfoto am 2015-08-19 um 22 25 31
http://subtlepatterns.com/congruent-pentagon-outline/

**Comment by sphinxc0re** [comment]
bildschirmfoto am 2015-08-19 um 22 40 33
http://subtlepatterns.com/escheresque-dark/

**Comment by sphinxc0re** [comment]
I made a little experiment here ;)
bildschirmfoto am 2015-08-19 um 22 43 06
http://subtlepatterns.com/dark-wood/

**Comment by sphinxc0re** [comment]
bildschirmfoto am 2015-08-19 um 22 45 55
http://subtlepatterns.com/dark-brick-wall/

**Comment by sphinxc0re** [comment]
cuberite_background_g
I'll try this background, too

**Comment by sphinxc0re** [comment]
bildschirmfoto am 2015-08-19 um 22 53 45

**Comment by sphinxc0re** [comment]
probably a little bit darker but this seems to be okay

**Comment by mathiascode** [comment]
I made the green color a little brighter, as you asked.
http://mathias-github.github.io/cuberite-redesign/

Anything else you want added to the blog? I'll fix the top padding and icon soon. EDIT: Fixed.

What should the favicon be? The symbolic icon?

**Comment by sphinxc0re** [comment]
The favicon should be the symbolic icon. The blog should contain one initial post

**Comment by tigerw** [comment]
The last background isn't bad.

**Comment by mathiascode** [comment]
I don't think the last background fits with this kind of design. It's too distracting and the borders are too dark.

**Comment by madmaxoft** [comment]
How about this variation on the background? Just a blur to make it less distracting. (Sorry, I don't know how to put it into the webpage for a screenshot). You need to view it in full zoom for the blur to actually be visible :)
cuberite_background_blur4

**Comment by sphinxc0re** [comment]
Nice. I'll create a screenshot when I'm back from work

**Comment by mathiascode** [comment]
How's the current background? http://mathias-github.github.io/cuberite-redesign/

**Comment by sphinxc0re** [comment]
Not enough depth

**Comment by sphinxc0re** [comment]
bildschirmfoto am 2015-08-25 um 19 15 11

**Comment by mathiascode** [comment]
Could we keep the green color scheme?

**Comment by mathiascode** [comment]
What about now? I took the first pattern you suggested and made it green. http://mathias-github.github.io/cuberite-redesign/

**Comment by tigerw** [comment]
Don't forget to add some lens flare too.

**Comment by sphinxc0re** [comment]
If you want to keep the green theme, you have to make it a brighter green like nearly _lime_

**Comment by mathiascode** [comment]
Alright, I'll do that asap. :)

**Comment by sphinxc0re** [comment]
What is up with this PR? Any updates. I want to get this merged. Also @mathias-github you should consider this article: https://github.com/blog/2053-easier-feeds-for-github-pages

**Comment by mathiascode** [comment]
How's the background color now? Still too dark or?

I'll take a look at the article.

**Comment by mathiascode** [comment]
Thanks for the link! I've added a feed to the site now. http://mathias-github.github.io/cuberite-redesign/feed.xml

**Comment by sphinxc0re** [comment]
The background still lacks of depth. I would prefer if you'd bring the blurry grey scheme back in

**Comment by mathiascode** [comment]
I could bring the gray color scheme or some of your gray patterns back into the design, but I don't personally think the gray background with cubes fits in with this type of design at all.

**Comment by tigerw** [comment]
Nah, the cubes look nice :)

**Comment by mathiascode** [comment]
I don't know... it just looks so out of place and distracting to me. Is there any other background that looks alright to you?

Sorry for being so difficult.

**Comment by tigerw** [comment]
I don't mind what you choose, just saying the cubes are alright, for me at least.

**Comment by sphinxc0re** [comment]
This takes way too long. I think it's about time to close this. @mathias-github please come back with a new PR and present your change again. This PR is completely messed up.

**Comment by mathiascode** [comment]
Will do once exam week is over.

**Comment by SafwatHalaby** [comment]
The live preview works perfectly even when JS is disabled.

**Comment by sphinxc0re** [comment]
Yep, that's css transitions

**Pull request closed without merging**
