### PR TITLE
Changed link to manual to link to wiki

### PR DESCRIPTION
**Pull request by sphinxc0re**
Preview: http://sphinxc0re.github.io/mc-server.github.io/

### CODE REVIEW

**Comment by NiLSPACE** [comment]
Wiki and the book are two different things as far as I know. The book should be a starter guide on how to set up and configure an MCServer.

**Comment by sphinxc0re** [comment]
I agree. But I talked to @bearbin about that and he is about to move the information from the book to the wiki. So I don't think it is still necessary to keep the link.

**Comment by bearbin** [comment]
I think they are still two separate things so the link should stay, although
I will copy some of the information over to the wiki.

On 22 February 2015 at 22:31, Julian Laubstein notifications@github.com
wrote:

> I agree. But I talked to @bearbin https://github.com/bearbin about that
> and he is about to move the information from the book to the wiki. So I
> don't think it is still necessary to keep the link.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mc-server/mc-server.github.io/pull/2#issuecomment-75467211
> .

## 

Alexander Harkness (bearbin)
Find my GPG key on the Ubuntu Keyserver - http://keyserver.ubuntu.com:11371/

**Comment by sphinxc0re** [comment]
So, in the future we have thousands and thousands of links and someone who actually wants to know something is totally confused. I think we can move everything to the Wiki and promote a "beginner's guide" on the front page. We have to keep the number of links down to avoid confusion.

**Comment by sphinxc0re** [comment]
merge?

**Comment by madmaxoft** [comment]
I agree with @SphinxC0re on this, we should keep the number of different information sources to minimum. I think the Book's contents would make a nice start for the wiki itself.

**Comment by sphinxc0re** [comment]
:tada: :balloon: :birthday: :dancer: :laughing:

**Comment by sphinxc0re** [comment]
Thoughts?

**Comment by sphinxc0re** [comment]
I thought the version tags would be more readable if they had a leading 'MC'

**Comment by madmaxoft** [comment]
Is there a place where we can preview the changes before deciding?

**Comment by sphinxc0re** [comment]
No I guess not. You can clone the repo and view it on you pc but since the repo doesn't have a gh-pages branch it is not possible

**Comment by madmaxoft** [comment]
The repo doesn't need `gh-pages` branch because, due to its name, the `master` branch is used for the web. And still that wouldn't help for previewing the PRs.

**Comment by sphinxc0re** [comment]
Then I can't help you. I don't know how Guthub websites are organised

**Comment by bearbin** [comment]
I could set up a bot for previewing changes, if you wanted me to. (It might take a few weeks though).

**Comment by sphinxc0re** [comment]
Is that really necessary?

**Comment by sphinxc0re** [comment]
Oops :laughing:

**Comment by madmaxoft** [comment]
How am I to judge a design change if I can't view it?
A bot would be nice, although there might already be something existing for this.

**Comment by sphinxc0re** [comment]
You can just clone it and view it

**Comment by sphinxc0re** [comment]
http://sphinxc0re.github.io/mc-server.github.io/
Here it is!

**Comment by sphinxc0re** [comment]
Because with these numbers we are not pointing to the version of MCServer but to the Minecraft version it works with

**Pull request merged**
