### PR TITLE
Added _blank target to links

### PR DESCRIPTION
**Pull request by sphinxc0re**
I thought that users as well as devs usually don't like getting moved from one page to another when they don't really know the first page. So I added a _blank target which let every link open in a new tab/ window (depending on the browser)

### CODE REVIEW

**Comment by worktycho** [comment]
This is completely against expected behaviour. I personally tend to want to go to the page I'm navigating to rather than having to open a new tab.  Also if you want to open a page that does not specify target blank you can just right click to force it in most modern browsers. It is much harder force a page to use the current window when it specifies target blank. And that's before you get into issues with pop-up blockers. This needs a much stronger UX justification than given.

**Comment by bearbin** [comment]
I don't agree with this change either. But the download links certainly don't need to open in a new tab, since browsers automatically do that.

**Comment by madmaxoft** [comment]
I don't really like this change. I prefer links to open in the _same_ page unless i middle-click them - so I'm fully in control what opens where.

**Comment by sphinxc0re** [comment]
Okay then :walking:

**Pull request closed without merging**
