### PR TITLE
Cuberite Newsletter 2019

### LINKED ISSUE #90: Newsletter for 2019
A newsletter listing changes made to Cuberite since September 2017 would be nice to have.

### PR DESCRIPTION
**Pull request by mathiascode**
Here's an initial draft for a 2019 newsletter. Are there any notable changes since September 2017 that I forgot to include?

Fixes #90

### CODE REVIEW

**Comment by mathiascode** [comment]
Should be ready now. In any case, @bearbin should send this post in a newsletter email before it's merged.

**Comment by mathiascode** [comment]
@bearbin Apologies for pinging, but could you look into getting the Android and FreeBSD builds up and running again, before we release this newsletter? They have been down for a couple of months.

**Review by madmaxoft — APPROVED** [review]

**Comment by bearbin** [comment]
Looks good to merge to me as well. 

I can get the Android build up and running tomorrow, I just need to make a few housekeeping changes to the image (updating the GCC version etc). I can't get the FreeBSD build working as we no longer have access to a FreeBSD server to run the builds on.

I will send the email once the android builds are running and then merge.

**Comment by mathiascode** [comment]
Thanks! Are you in control of the Cuberite Twitter profile, or do you know who has access to it?

**Comment by mathiascode** [comment]
If/when someone else merges this, remember to change the post date.

**Comment by madmaxoft** [comment]
The 2019 newsletter in 2020... :) Why not just merge it already? What's the process?

**Comment by mathiascode** [comment]
The new Android version is out, so I'm merging this to prevent further delays. 

@bearbin Send the newsletter when you have time.

**Pull request merged**
