### PR TITLE
New Discuss-page and other changes

### PR DESCRIPTION
**Pull request by mathiascode**
- New Discuss-page with information about the IRC channel
- Updated Support-page with email address
- Slightly brighter gray background color, since the old one looked pitch black on some screens
- Slightly larger Support-icon
- Updated icon font with Discuss-icon and FreeBSD-icon for potential download button in the future

Live demo: http://final.cuberite.ga

### CODE REVIEW

**Comment by sphinxc0re** [comment]
What about #22 ?

**Comment by mathiascode** [comment]
I'll include that one as well. Thanks for notifying me!

**Comment by sphinxc0re** [comment]
It would be nice, if any icon'y logo could be like that. So iOS, Android, Desktop logo for fav/shortcuticon: all the same

**Comment by mathiascode** [comment]
Alright, the icons are updated now.

**Pull request merged**
