### PR TITLE
Added link to GitHub repo & commit approx

### PR DESCRIPTION
**Pull request by williamhatcher**
And @bearbin  didn't think it could be done, https://github.com/cuberite/cuberite/issues/3949#issuecomment-324107059

### CODE REVIEW

**Comment by mathiascode** [comment]
I'll review this PR later today.

**Comment by bearbin** [comment]
The link to the website source is a good idea, but the commit id is useless - not only is it not the actual commit ID from the source but it has no purpose (why do website viewers need to know the latest commit ID?)

Also, it makes the website use javascript for functionality, which we have successfully avoided so far.

**Comment by mathiascode** [comment]
I agree with bearbin. The link to the repo is good, but I don't see why we should show the commit ID on the website.

**Comment by madmaxoft** [comment]
It could be useful to have the commit hash on the website, but it needn't be visible to end-users. Putting it into a comment in the HTML code would allow us devs to check stuff.

Of course, that is all assuming that the commit hash is correct. If it isn't, then there's really no point.

**Comment by mathiascode** [comment]
A HTML comment sounds like a good idea. We could do this without Javascript by adding the "jekyll-github-meta" gem to _config.yml, and this line in _layouts/default.html.
`<!-- Website commit: {{ site.github.build_revision }} -->`

View the source code of https://mathiascode.github.io/cuberite-website-changes/ as an example.

**Comment by williamhatcher** [comment]
Thanks, @mathiascode.
I removed the JS for getting the commit sha and added your suggestion.

**Pull request merged**
