### PR TITLE
New design for cuberite.org

### PR DESCRIPTION
**Pull request by mathiascode**
New pull request, since the old one became too messy. This one is ready to be merged.

Live preview: http://final.cuberite.ga
(The post duplicates seen in the live preview do not exist in the pull request, they are simply there to demonstrate the pagination)

### CODE REVIEW

**Comment by NiLSPACE** [comment]
It's a little.. dark ;)

**Comment by mathiascode** [comment]
Some want it to be dark, some want it to be light. Does the majority want a dark, light or slightly lighter color scheme?

**Comment by tigerw** [comment]
Psychedelic; cycling from black to white with a 500ms interval.

**Comment by bearbin** [comment]
I generally prefer light, but your design looks great, so no problems with it being merged as it is.

**Comment by sphinxc0re** [comment]
Nice one

**Comment by mathias-github** [comment]
Thanks!

Don't merge this until I've changed a silly mistake in the PR, as it could affect the SEO (no need to manually add "permalink" to pages, since GitHub automatically serves pages without the .html extension. This means we can get rid of the trailing slash after URLs (eg. http://cuberite.org/support instead of http://cuberite.org/support/)).

**Comment by mathiascode** [comment]
Thanks! Looks like this may finally get merged after all. :P

**Comment by NiLSPACE** [comment]
Anyone against a merge?

**Comment by sphinxc0re** [comment]
I have one tiny objection. One can't see the compatible MC version.
My suggestion: Put a little headline above the downloads that says 'Download for Minecraft 1.8.8'

**Comment by mathiascode** [comment]
I'll do that :D

**Comment by sphinxc0re** [comment]
Wow! That was fast!

**Comment by mathiascode** [comment]
Indeed :P

Something like this? http://final.cuberite.ga/

**Comment by sphinxc0re** [comment]
Nice. Merge If no other objections in the next two days

**Comment by mathiascode** [comment]
Sounds good!

**Comment by madmaxoft** [comment]
We are compatible with clients 1.7 to 1.8.8, perhaps it might be stated there instead of the single version.

**Comment by mathiascode** [comment]
I changed the text to "Download for Minecraft 1.7 & 1.8"

**Comment by mathiascode** [comment]
So, merge today?

**Comment by madmaxoft** [comment]
Why not :P

**Comment by mathiascode** [comment]
Thanks!

**Comment by madmaxoft** [comment]
For some reason the webpage is still showing the old design for me. Perhaps it needs some time to rebuild?

**Comment by mathiascode** [comment]
Now it shows up. Looks like I forgot to include a padding change for the new "Download for Minecraft 1.7 & 1.8" text. I'll create a pull request to address that asap.

**Pull request merged**
